# copy this file as config.yml and do not commit the copied file

# if gsheet read times out how many seconds to wait before trying the next read
gsheet-read-wait-seconds:   60

# if gsheet read times out how many times the read should be tried in total
gsheet-read-try-count:      5

dirs:
  # all outputs and temporary downloads go here
  output-dir:            "../../out"

files:
  # the google service account credential for accessing the gsheet(s) (this file must never be in the repo)
  google-cred:           "./credential.json"
