graph:
    attributes:
        clusterrank:    "local"
        splines:        "ortho"
        compound:       "true"
        # ratio:        "auto"
        ranksep:        "0.5 equally"
        nodesep:        "1.0"
        esep:           "+30"
        sep:            "+20"

    node:
        fixedsize:      "true"
        style:          "rounded, filled"
        fillcolor:      "#FFFFFF"
        color:          "#000000"
        penwidth:       "0.5"
        fontname:       "Arial"
        fontsize:       "10pt"
        margin:         "0.20,0.20"
    
    edge:
        fillcolor:      "#F8F8F8"
        color:          "#202020"
        penwidth:       "0.5"
        fontname:       "Helvetica"
        fontsize:       "8pt"

pool:
    graph:
        style:          "filled"
        color:          "#D0D0D0"
        penwidth:       "0.5"
        fillcolor:      "#FFFFFF"
        fontname:       "Helvetica"
        fontcolor:      "#202020"
        fontsize:       "16pt"
        margin:          "10,10"    

lane:
        style:          "filled"
        color:          "#D0D0D0"
        penwidth:       "0.5"
        fillcolor:      "#F8F8F8"
        fontname:       "Helvetica"
        fontcolor:      "#202020"
        fontsize:       "14pt"
        margin:         "30,20"    
