graph:
    attributes:
        clusterrank:    "local"
        splines:        "ortho"
        compound:       "true"
        ratio:          "auto"
        concentrate:    "false"
        ranksep:        "0.5 equally"
        nodesep:        "1.0"
        esep:           "+30"
        sep:            "+20"

    node:
        fixedsize:      "true"
        style:          "filled"
        fillcolor:      "#FFFFFF"
        color:          "#000000"
        penwidth:       "0.5"
        fontname:       "Noto Sans"
        fontsize:       "10pt"
        margin:         "0.20,0.20"
        width:          "1.5in"
    
    edge:
        fillcolor:      "#F8F8F8"
        color:          "#202020"
        penwidth:       "0.5"
        fontname:       "Noto Sans"
        fontsize:       "8pt"
        style:          "solid"

pool:
    graph:
        style:          "filled"
        color:          "#D0D0D0"
        penwidth:       "0.5"
        fillcolor:      "#FFFFFF"
        fontname:       "Arial"
        fontcolor:      "#202020"
        fontsize:       "16pt"
        margin:         "10,10"    

lane:
    graph:
        style:          "filled"
        color:          "#D0D0D0"
        penwidth:       "0.5"
        fillcolor:      "#F8F8F8"
        fontname:       "Arial"
        fontcolor:      "#202020"
        fontsize:       "14pt"
        margin:         "30,20"

node:
    wrap-at:                                    12
    shapes:
        # start events
        start:                                  shape='circle'; width='0.75in';
        start-compensation:                     ''
        start-conditional:                      ''
        start-conditional-non:                  ''
        start-error:                            ''
        start-escalation:                       ''
        start-escalation-non:                   ''
        start-message:                          shape='Mdiamond'; width='1.5in';
        start-message-non:                      ''
        start-multiple:                         ''
        start-multiple-non:                     ''
        start-parallel-multiple:                ''
        start-parallel-multiple-non:            ''
        start-signal:                           ''
        start-signal-non:                       ''
        start-timer:                            ''
        start-timer-non:                        ''

        # end events
        end:                                    shape='doublecircle'; width='0.75in';
        end-cancel:                             ''
        end-compensation:                       ''
        end-error:                              ''
        end-escalation:                         ''
        end-message:                            ''
        end-multiple:                           ''
        end-signal:                             ''
        end-terminate:                          shape='doublecircle'; width='0.75in';

        # intermediate events
        intermediate:                           ''
        catch-cancel:                           ''
        catch-compensation:                     ''
        throw-compensation:                     ''
        catch-error:                            ''
        catch-escalation:                       ''
        catch-escalation-non:                   ''
        throw-escalation:                       ''
        catch-link:                             ''
        throw-link:                             ''
        catch-message:                          ''
        catch-message-non:                      ''
        throw-message:                          shape='doublecircle'; width='0.75in';
        catch-multiple:                         ''
        catch-multiple-non:                     ''
        throw-multiple:                         ''
        catch-parallel-multiple:                ''
        catch-parallel-multiple-non:            ''
        catch-signal:                           ''
        catch-signal-non:                       ''
        throw-signal:                           ''
        conditional:                            ''
        conditional-non:                        ''
        timer:                                  shape='doublecircle'; width='0.75in';
        timer-non:                              ''

        # task activities
        task:                                   shape='rectangle'; style='rounded, filled';
        business-rule-task:                     ''
        manual-task:                            ''
        receive-task:                           ''
        script-task:                            ''
        send-task:                              ''
        service-task:                           ''
        user-task:                              ''

        # call activities
        call:                                   ''
        business-rule-call:                     ''
        manual-call:                            ''
        script-call:                            ''
        user-call:                              ''

        # subprocess activities
        process:                                ''
        adhoc:                                  ''
        transaction:                            ''

        # event subprocess activities
        event:                                  ''
        event-compensation:                     ''
        event-conditional:                      ''
        event-conditional-non:                  ''
        event-error:                            ''
        event-escalation:                       ''
        event-escalation-non:                   ''
        event-message:                          ''
        event-message-non:                      ''
        event-multiple:                         ''
        event-multiple-non:                     ''
        event-parallel-multiple:                ''
        event-parallel-multiple-non:            ''
        event-signal:                           ''
        event-signal-non:                       ''
        event-timer:                            ''
        event-timer-non:                        ''

        # gateways
        exclusive:                              ''
        inclusive:                              ''
        parallel:                               shape='diamond'; width='1.5in';
        complex:                                ''
        event-based:                            shape='diamond'; width='1.5in';
        event-based-start:                      ''
        event-based-parallel-start:             ''

        # data
        data:                                   ''
        data-collection:                        ''
        data-input:                             ''
        data-input-collection:                  ''
        data-output:                            ''
        data-output-collection:                 ''
        data-store:                             ''

edge:
    shapes:
        sequence:                               ''
        message:                                style=dashed;
        association:                            ''
        directed-association:                   ''
        bidirectional-association:              ''