graph:
    attributes:
        clusterrank:    "local"
        splines:        "ortho"
        compound:       "true"
        ratio:          "auto"
        concentrate:    "false"
        ranksep:        "0.5"
        nodesep:        "1.0"
        minlen:          "0"
        forcelabels:     "true"

    node:
        fixedsize:      "true"
        style:          "filled"
        fillcolor:      "#FFFFFF"
        color:          "#000000"
        penwidth:       "0.5"
        fontname:       "Noto Sans"
        fontsize:       "10pt"
        margin:         "0.20,0.20"
        width:          "1.5in"
    
    edge:
        fillcolor:      "#606060"
        color:          "#202020"
        penwidth:       "0.5"
        fontname:       "Noto Sans"
        fontsize:       "8pt"
        style:          "solid"

pool:
    graph:
        style:          "filled"
        color:          "#D0D0D0"
        penwidth:       "0.5"
        fillcolor:      "#FFFFFF"
        fontname:       "Arial"
        fontcolor:      "#202020"
        fontsize:       "16pt"
        margin:         "10,10"    

lane:
    graph:
        style:          "filled"
        color:          "#D0D0D0"
        penwidth:       "0.5"
        fillcolor:      "#F8F8F8"
        fontname:       "Arial"
        fontcolor:      "#202020"
        fontsize:       "14pt"
        margin:         "30,20"

node:
    wrap-at:                                    10
    shapes:
        # start events
        start:                                  shape='circle'; fontsize="8pt"; width='0.5in'; 
        start-compensation:                     shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-compensation.png";
        start-conditional:                      shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-conditional.png";
        start-conditional-non:                  shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-conditional-non.png";
        start-error:                            shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-error.png";
        start-escalation:                       shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-escalation.png";
        start-escalation-non:                   shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-escalation-non.png";
        start-message:                          shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-message.png";
        start-message-non:                      shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-message-non.png";
        start-multiple:                         shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-multiple.png";
        start-multiple-non:                     shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-multiple-non.png";
        start-parallel-multiple:                shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-parallel-multiple.png";
        start-parallel-multiple-non:            shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-parallel-multiple-non.png";
        start-signal:                           shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-signal.png";
        start-signal-non:                       shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-signal-non.png";
        start-timer:                            shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-timer.png";
        start-timer-non:                        shape='circle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/start/start-timer-non.png";

        # end events
        end:                                    shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; 
        end-cancel:                             shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-cancel.png";
        end-compensation:                       shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-compensation.png";
        end-error:                              shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-error.png";
        end-escalation:                         shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-escalation.png";
        end-message:                            shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-message.png";
        end-multiple:                           shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-multiple.png";
        end-signal:                             shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-signal.png";
        end-terminate:                          shape='circle'; fontsize="8pt"; penwidth='3.0'; width='0.5in'; image="./bpmn/event/end/end-terminate.png";

        # intermediate events
        intermediate:                           shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/intermediate.png";
        catch-cancel:                           shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-cancel.png";
        catch-compensation:                     shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-compensation.png";
        throw-compensation:                     shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/throw-compensation.png";
        catch-error:                            shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-error.png";
        catch-escalation:                       shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-escalation.png";
        catch-escalation-non:                   shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-escalation-non.png";
        throw-escalation:                       shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/throw-escalation.png";
        catch-link:                             shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-link.png";
        throw-link:                             shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/throw-link.png";
        catch-message:                          shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-message.png";
        catch-message-non:                      shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-message-non.png";
        throw-message:                          shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/throw-message.png";
        catch-multiple:                         shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-multiple.png";
        catch-multiple-non:                     shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-multiple-non.png";
        throw-multiple:                         shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/throw-multiple.png";
        catch-parallel-multiple:                shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-parallel-multiple.png";
        catch-parallel-multiple-non:            shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-parallel-multiple-non.png";
        catch-signal:                           shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-signal.png";
        catch-signal-non:                       shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/catch-signal-non.png";
        throw-signal:                           shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/throw-signal.png";
        conditional:                            shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/conditional.png";
        conditional-non:                        shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/conditional-non.png";
        timer:                                  shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/timer.png";
        timer-non:                              shape='doublecircle'; fontsize="8pt"; width='0.5in'; image="./bpmn/event/intermediate/timer-non.png";

        # task activities
        task:                                   shape='rectangle'; style='rounded, filled';
        business-rule-task:                     shape='rectangle'; style='rounded, filled';
        manual-task:                            shape='rectangle'; style='rounded, filled';
        receive-task:                           shape='rectangle'; style='rounded, filled';
        script-task:                            shape='rectangle'; style='rounded, filled';
        send-task:                              shape='rectangle'; style='rounded, filled';
        service-task:                           shape='rectangle'; style='rounded, filled';
        user-task:                              shape='rectangle'; style='rounded, filled';

        # call activities
        call:                                   shape='rectangle'; penwidth='3.0'; style='rounded, filled';
        business-rule-call:                     shape='rectangle'; penwidth='3.0'; style='rounded, filled';
        manual-call:                            shape='rectangle'; penwidth='3.0'; style='rounded, filled';
        script-call:                            shape='rectangle'; penwidth='3.0'; style='rounded, filled';
        user-call:                              shape='rectangle'; penwidth='3.0'; style='rounded, filled';

        # subprocess activities
        process:                                shape='rectangle'; style='rounded, filled';
        adhoc:                                  shape='rectangle'; style='rounded, filled';
        transaction:                            shape='rectangle'; style='rounded, filled';

        # event subprocess activities
        event:                                  shape='rectangle'; style='dotted, filled';
        event-compensation:                     shape='rectangle'; style='dotted, filled';
        event-conditional:                      shape='rectangle'; style='dotted, filled';
        event-conditional-non:                  shape='rectangle'; style='dotted, filled';
        event-error:                            shape='rectangle'; style='dotted, filled';
        event-escalation:                       shape='rectangle'; style='dotted, filled';
        event-escalation-non:                   shape='rectangle'; style='dotted, filled';
        event-message:                          shape='rectangle'; style='dotted, filled';
        event-message-non:                      shape='rectangle'; style='dotted, filled';
        event-multiple:                         shape='rectangle'; style='dotted, filled';
        event-multiple-non:                     shape='rectangle'; style='dotted, filled';
        event-parallel-multiple:                shape='rectangle'; style='dotted, filled';
        event-parallel-multiple-non:            shape='rectangle'; style='dotted, filled';
        event-signal:                           shape='rectangle'; style='dotted, filled';
        event-signal-non:                       shape='rectangle'; style='dotted, filled';
        event-timer:                            shape='rectangle'; style='dotted, filled';
        event-timer-non:                        shape='rectangle'; style='dotted, filled';

        # gateways
        exclusive:                              shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/exclusive.png";
        inclusive:                              shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/inclusive.png";
        parallel:                               shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/parallel.png";
        complex:                                shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/complex.png";
        event-based:                            shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/event-based.png";
        event-based-start:                      shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/event-based-start.png";
        event-based-parallel-start:             shape='diamond'; fontsize="8pt"; width='0.5in'; image="./bpmn/gateway/event-based-parallel-start.png";

        # data
        data:                                   shape='note'; style='filled';
        data-collection:                        shape='note'; style='filled';
        data-input:                             shape='note'; style='filled';
        data-input-collection:                  shape='note'; style='filled';
        data-output:                            shape='note'; style='filled';
        data-output-collection:                 shape='note'; style='filled';
        data-store:                             shape='cylinder'; style='filled';

edge:
    shapes:
        sequence:                               style='solid, filled'; arrowhead=normal;
        message:                                style=dashed; arrowhead=empty;
        association:                            style=dotted; arrowhead=none;
        directed-association:                   style=dotted; arrowhead=open;
        bidirectional-association:              style=dotted; dir=both; arrowhead=open; arrowtail=open;