defs:
  style:
    text-anchor:        "middle"
    dominant-baseline:  "middle"
    font-family:        "arial"
    font-size:          12
    font-weight:        "normal"
    fill:               "#02066F"
    stroke:             "#000000"
    stroke-width:       1
  
  text:

bpmn:
pool:
lane:
band:
node:
edge:
head:
tail: